"""updated the Documents model and schema

Revision ID: a9e73ea5d1b8
Revises: 51b2c7ffdd8c
Create Date: 2026-02-23 16:50:09.999764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9e73ea5d1b8'
down_revision: Union[str, Sequence[str], None] = '51b2c7ffdd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.alter_column('documents', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('documents', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'uploaded_at')
    # ### end Alembic commands ###
